#############################################################################
# Makefile for building: Axomae
# Generated by qmake (3.1) (Qt 5.9.4)
# Project:  Axomae.pro
# Template: app
# Command: /usr/bin/qmake-qt5 -o Makefile Axomae.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++17 -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/SDL2 -I/usr/local/cuda/include -isystem /usr/include/libdrm -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake-qt5 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake-qt5 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Axomae1.0.0
DISTDIR = /home/HamilcarR/Desktop/Projets/Axomae/.tmp/Axomae1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -L/lib -L/usr/local/cuda/lib64 -L/usr/lib64 -lSDL2 -ldl -lSDL2_image -lassimp -lcudart -lcuda -lGL -lQt5Widgets -lQt5Gui -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = sources/Controller.cpp \
		sources/GUIWindow.cpp \
		sources/ImageImporter.cpp \
		sources/ImageManager.cpp \
		sources/main.cpp \
		sources/Model.cpp \
		sources/Syntax.cpp \
		sources/TerminalOpt.cpp \
		sources/View.cpp \
		sources/Window.cpp qrc_Resource.cpp \
		moc_GUIWindow.cpp
OBJECTS       = Kernel.o \
		Controller.o \
		GUIWindow.o \
		ImageImporter.o \
		ImageManager.o \
		main.o \
		Model.o \
		Syntax.o \
		TerminalOpt.o \
		View.o \
		Window.o \
		qrc_Resource.o \
		moc_GUIWindow.o
DIST          = /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		Axomae.pro Form\ Files/test.h \
		includes/constants.h \
		includes/Controller.h \
		includes/GUIWindow.h \
		includes/ImageImporter.h \
		includes/ImageManager.h \
		includes/images.h \
		includes/Model.h \
		includes/Renderer.h \
		includes/Syntax.h \
		includes/TerminalOpt.h \
		includes/View.h \
		includes/Window.h sources/Controller.cpp \
		sources/GUIWindow.cpp \
		sources/ImageImporter.cpp \
		sources/ImageManager.cpp \
		sources/main.cpp \
		sources/Model.cpp \
		sources/Syntax.cpp \
		sources/TerminalOpt.cpp \
		sources/View.cpp \
		sources/Window.cpp
QMAKE_TARGET  = Axomae
DESTDIR       = 
TARGET        = Axomae


first: all
####### Build rules

$(TARGET): ui_test.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Axomae.pro /usr/lib64/qt5/mkspecs/linux-g++/qmake.conf /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		Axomae.pro \
		Ressources/Resource.qrc \
		/usr/lib64/libQt5Widgets.prl \
		/usr/lib64/libQt5Gui.prl \
		/usr/lib64/libQt5Core.prl
	$(QMAKE) -o Makefile Axomae.pro
/usr/lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/usr/lib64/qt5/mkspecs/qconfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_AkonadiMime.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt5/mkspecs/features/qt_functions.prf:
/usr/lib64/qt5/mkspecs/features/qt_config.prf:
/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt5/mkspecs/features/toolchain.prf:
/usr/lib64/qt5/mkspecs/features/default_pre.prf:
/usr/lib64/qt5/mkspecs/features/resolve_config.prf:
/usr/lib64/qt5/mkspecs/features/default_post.prf:
/usr/lib64/qt5/mkspecs/features/warn_on.prf:
/usr/lib64/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt5/mkspecs/features/qt.prf:
/usr/lib64/qt5/mkspecs/features/resources.prf:
/usr/lib64/qt5/mkspecs/features/moc.prf:
/usr/lib64/qt5/mkspecs/features/uic.prf:
/usr/lib64/qt5/mkspecs/features/unix/thread.prf:
/usr/lib64/qt5/mkspecs/features/qmake_use.prf:
/usr/lib64/qt5/mkspecs/features/file_copies.prf:
/usr/lib64/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt5/mkspecs/features/exceptions.prf:
/usr/lib64/qt5/mkspecs/features/yacc.prf:
/usr/lib64/qt5/mkspecs/features/lex.prf:
Axomae.pro:
Ressources/Resource.qrc:
/usr/lib64/libQt5Widgets.prl:
/usr/lib64/libQt5Gui.prl:
/usr/lib64/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Axomae.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents kernels/Kernel.cu $(DISTDIR)/
	$(COPY_FILE) --parents Ressources/Resource.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib64/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Form\ Files/test.h includes/constants.h includes/Controller.h includes/GUIWindow.h includes/ImageImporter.h includes/ImageManager.h includes/images.h includes/Model.h includes/Renderer.h includes/Syntax.h includes/TerminalOpt.h includes/View.h includes/Window.h $(DISTDIR)/
	$(COPY_FILE) --parents sources/Controller.cpp sources/GUIWindow.cpp sources/ImageImporter.cpp sources/ImageManager.cpp sources/main.cpp sources/Model.cpp sources/Syntax.cpp sources/TerminalOpt.cpp sources/View.cpp sources/Window.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Form\ Files/test.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_cuda_make_all: Kernel.o
compiler_cuda_clean:
	-$(DEL_FILE) Kernel.o
Kernel.o: kernels/Kernel.cuh \
		includes/constants.h \
		/usr/local/cuda/include/cuda.h \
		/usr/local/cuda/include/cuda_device_runtime_api.h \
		/usr/local/cuda/include/driver_types.h \
		/usr/local/cuda/include/crt/host_defines.h \
		/usr/local/cuda/include/vector_types.h \
		/usr/local/cuda/include/cuda_runtime_api.h \
		/usr/local/cuda/include/builtin_types.h \
		/usr/local/cuda/include/device_types.h \
		/usr/local/cuda/include/surface_types.h \
		/usr/local/cuda/include/texture_types.h \
		/usr/local/cuda/include/device_launch_parameters.h \
		kernels/Kernel.cu
	nvcc -m64 -arch=sm_61 -c kernels/*.cu -o Kernel.o -lcuda -lcudart -lSDL2

compiler_rcc_make_all: qrc_Resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_Resource.cpp
qrc_Resource.cpp: Ressources/Resource.qrc \
		/usr/lib64/qt5/bin/rcc \
		Ressources/nvidia-cuda21.png
	/usr/lib64/qt5/bin/rcc -name Resource Ressources/Resource.qrc -o qrc_Resource.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib64/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=c++17 -g -Wall -W -dM -E -o moc_predefs.h /usr/lib64/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_GUIWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_GUIWindow.cpp
moc_GUIWindow.cpp: includes/ImageImporter.h \
		includes/Model.h \
		includes/ImageManager.h \
		kernels/Kernel.cuh \
		includes/constants.h \
		/usr/local/cuda/include/cuda.h \
		/usr/local/cuda/include/cuda_device_runtime_api.h \
		/usr/local/cuda/include/driver_types.h \
		/usr/local/cuda/include/crt/host_defines.h \
		/usr/local/cuda/include/vector_types.h \
		/usr/local/cuda/include/cuda_runtime_api.h \
		/usr/local/cuda/include/builtin_types.h \
		/usr/local/cuda/include/device_types.h \
		/usr/local/cuda/include/surface_types.h \
		/usr/local/cuda/include/texture_types.h \
		/usr/local/cuda/include/device_launch_parameters.h \
		includes/Renderer.h \
		includes/Window.h \
		includes/images.h \
		Form\ Files/test.h \
		includes/GUIWindow.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/HamilcarR/Desktop/Projets/Axomae -I/usr/include/SDL2 -I/usr/local/cuda/include -I/usr/include/libdrm -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include -I-I/usr/include/c++/7 includes/GUIWindow.h -o moc_GUIWindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_test.h
compiler_uic_clean:
	-$(DEL_FILE) ui_test.h
ui_test.h: Form\ Files/test.ui \
		/usr/lib64/qt5/bin/uic
	/usr/lib64/qt5/bin/uic Form\ Files/test.ui -o ui_test.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_cuda_clean compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

Controller.o: sources/Controller.cpp includes/Controller.h \
		includes/Model.h \
		includes/View.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Controller.o sources/Controller.cpp

GUIWindow.o: sources/GUIWindow.cpp includes/GUIWindow.h \
		includes/ImageImporter.h \
		includes/Model.h \
		includes/ImageManager.h \
		kernels/Kernel.cuh \
		includes/constants.h \
		/usr/local/cuda/include/cuda.h \
		/usr/local/cuda/include/cuda_device_runtime_api.h \
		/usr/local/cuda/include/driver_types.h \
		/usr/local/cuda/include/crt/host_defines.h \
		/usr/local/cuda/include/vector_types.h \
		/usr/local/cuda/include/cuda_runtime_api.h \
		/usr/local/cuda/include/builtin_types.h \
		/usr/local/cuda/include/device_types.h \
		/usr/local/cuda/include/surface_types.h \
		/usr/local/cuda/include/texture_types.h \
		/usr/local/cuda/include/device_launch_parameters.h \
		includes/Renderer.h \
		includes/Window.h \
		includes/images.h \
		Form\ Files/test.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GUIWindow.o sources/GUIWindow.cpp

ImageImporter.o: sources/ImageImporter.cpp includes/ImageImporter.h \
		includes/Model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImageImporter.o sources/ImageImporter.cpp

ImageManager.o: sources/ImageManager.cpp includes/ImageManager.h \
		kernels/Kernel.cuh \
		includes/constants.h \
		/usr/local/cuda/include/cuda.h \
		/usr/local/cuda/include/cuda_device_runtime_api.h \
		/usr/local/cuda/include/driver_types.h \
		/usr/local/cuda/include/crt/host_defines.h \
		/usr/local/cuda/include/vector_types.h \
		/usr/local/cuda/include/cuda_runtime_api.h \
		/usr/local/cuda/include/builtin_types.h \
		/usr/local/cuda/include/device_types.h \
		/usr/local/cuda/include/surface_types.h \
		/usr/local/cuda/include/texture_types.h \
		/usr/local/cuda/include/device_launch_parameters.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImageManager.o sources/ImageManager.cpp

main.o: sources/main.cpp includes/ImageManager.h \
		kernels/Kernel.cuh \
		includes/constants.h \
		/usr/local/cuda/include/cuda.h \
		/usr/local/cuda/include/cuda_device_runtime_api.h \
		/usr/local/cuda/include/driver_types.h \
		/usr/local/cuda/include/crt/host_defines.h \
		/usr/local/cuda/include/vector_types.h \
		/usr/local/cuda/include/cuda_runtime_api.h \
		/usr/local/cuda/include/builtin_types.h \
		/usr/local/cuda/include/device_types.h \
		/usr/local/cuda/include/surface_types.h \
		/usr/local/cuda/include/texture_types.h \
		/usr/local/cuda/include/device_launch_parameters.h \
		includes/ImageImporter.h \
		includes/Model.h \
		includes/Window.h \
		includes/images.h \
		includes/TerminalOpt.h \
		includes/Renderer.h \
		includes/GUIWindow.h \
		Form\ Files/test.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o sources/main.cpp

Model.o: sources/Model.cpp includes/Model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Model.o sources/Model.cpp

Syntax.o: sources/Syntax.cpp includes/Syntax.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Syntax.o sources/Syntax.cpp

TerminalOpt.o: sources/TerminalOpt.cpp includes/ImageImporter.h \
		includes/Model.h \
		includes/TerminalOpt.h \
		includes/ImageManager.h \
		kernels/Kernel.cuh \
		includes/constants.h \
		/usr/local/cuda/include/cuda.h \
		/usr/local/cuda/include/cuda_device_runtime_api.h \
		/usr/local/cuda/include/driver_types.h \
		/usr/local/cuda/include/crt/host_defines.h \
		/usr/local/cuda/include/vector_types.h \
		/usr/local/cuda/include/cuda_runtime_api.h \
		/usr/local/cuda/include/builtin_types.h \
		/usr/local/cuda/include/device_types.h \
		/usr/local/cuda/include/surface_types.h \
		/usr/local/cuda/include/texture_types.h \
		/usr/local/cuda/include/device_launch_parameters.h \
		includes/Window.h \
		includes/images.h \
		includes/Renderer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TerminalOpt.o sources/TerminalOpt.cpp

View.o: sources/View.cpp includes/View.h \
		includes/Controller.h \
		includes/Model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o View.o sources/View.cpp

Window.o: sources/Window.cpp includes/Window.h \
		includes/images.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Window.o sources/Window.cpp

qrc_Resource.o: qrc_Resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Resource.o qrc_Resource.cpp

moc_GUIWindow.o: moc_GUIWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GUIWindow.o moc_GUIWindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

