#ifndef API_COMMON_H
#define API_COMMON_H
#include <memory>
namespace nova {
  enum ERROR_STATE {
    SUCCESS,

    INVALID_ENGINE_STATE,
    INVALID_BUFFER_STATE,
    INVALID_CHANNEL_DESCRIPTOR,
    INVALID_SCENE_TYPE,
    INVALID_TRANSFORM_TYPE,
    SCENE_NOT_PROCESSED,

    NOT_GPU_BUILD,

    OUT_OF_MEMORY,
  };
}
#endif
