name: Build and Tests

on:
  push:
    branches:
    - "Feature-CI_CD"
    - "master"
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: RelWithDebInfo
  BUILD_TESTS : ON

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Axomae dependencies
      run: |
        cd ${{github.workspace}} && ./scripts/update_deps.sh

    - name: Install OpenGL and GLEW
      run: |
        sudo apt-get install -y libgl1-mesa-dev libglew-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/../build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DAXOMAE_BUILD_TESTS:BOOL=${{env.BUILD_TESTS}} -DAXOMAE_LUT_MEDIUMP:BOOL=ON -DAXOMAE_FROMSOURCE_QT_BUILD=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/../build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/../build
      run: ctest -C ${{env.BUILD_TYPE}}


    #####################################################
    # For debugging , opens an ssh cli
    # - name: Setup tmate session
    #  if: success() || failure()
    #  uses: mxschmitt/action-tmate@v3